Section A: Data Structures & Control Structures
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [3]:
list=[1,2,3,4,5]
list.append(10)
print(list)

[1, 2, 3, 4, 5, 10]


In [4]:
list.extend([10])
print(list)

[1, 2, 3, 4, 5, 10, 10]


In [5]:
list.insert(0,12)
print(list)

[12, 1, 2, 3, 4, 5, 10, 10]


In [6]:
list.remove(10)
print(list)

[12, 1, 2, 3, 4, 5, 10]


In [7]:
list.pop()

10

In [8]:
list.index(3)

3

In [9]:
list.count(4)


1

In [10]:
list.reverse()
print(list)

[5, 4, 3, 2, 1, 12]


In [11]:
list.sort()
print(list)

[1, 2, 3, 4, 5, 12]


In [12]:
list.clear()
print(list)

[]


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [14]:
tuple=('Anu',"Uma","Sanju") #Tuple is immutable , it does not store any duplicate values and it does not changes any elements in it
tuple.insert(1,"Kanchana")

AttributeError: 'tuple' object has no attribute 'insert'

3.	Create a set of integers with some duplicate values. Print the set and explain the output

In [15]:
set={1,2,3,4,5,5,5} #Set does not print any duplicate values
print(set)

{1, 2, 3, 4, 5}


4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary

In [16]:
dict={"name":"Mingyu","age":"28","city":"Anyang"}
print(dict)

{'name': 'Mingyu', 'age': '28', 'city': 'Anyang'}


In [17]:
dict.update({"age":"29"})

In [18]:
dict

{'name': 'Mingyu', 'age': '29', 'city': 'Anyang'}

In [19]:
dict["email"]="minmin@gmail.com"

In [22]:
dict

{'name': 'Mingyu', 'age': '29', 'city': 'Anyang', 'email': 'minmin@gmail.com'}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [23]:
age=int(input("Enter the age"))
if age>=18:
    print("You are eligeble for voting")
else:
    print("You are not eligeble for voting")

You are eligeble for voting


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [24]:
marks=int(input("Enter the number"))
if marks>=90:
    print("A")
elif marks>=75 and marks<=89:
    print("B")
elif marks>=50 and marks<=74:
    print("C")
else:
    print("Fail")

ValueError: invalid literal for int() with base 10: ''

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
num=int(input("Enter the number"))
if num>0:
    if num%2==0:
        print("Number is positive and even")
    else:
        
        print("Number is positive but not even")
elif num==0:
    print("Number is zero")
else:
    print("Number is negative")

Number is positive and even


Section B: Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [ ]:
import numpy as np
scalar=np.array(5)
print("Scalar is:",scalar)

array_1D=np.array([1,2,3,4,5])
print("1D array is:",array_1D)

array_2D=np.array([[10,20,30],
                  [40,50,60]])
print("2D array is:",array_2D)

Scalar is: 5
1D array is: [1 2 3 4 5]
2D array is: [[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
array=np.random.randint(0,101 ,size=(4,4))
print(array)

[[88 87 22 19]
 [48 99 99 98]
 [74 33 27 35]
 [83 93 14 12]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
import pandas as pd
data=np.array([[1,2,3],
               [10,20,30]])
print("Data:",data)
df=pd.DataFrame(data)
print("\n",df)
df1=pd.DataFrame(data,columns=('A','B','C'))
print("\n",df1)

Data: [[ 1  2  3]
 [10 20 30]]

     0   1   2
0   1   2   3
1  10  20  30

     A   B   C
0   1   2   3
1  10  20  30


Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [35]:
import numpy as np
import pandas as pd
DataFrame={
'Name':['Ankith','Arnav','Charles','Mini','Niki','Gopi','Kim','Steve','Praveen','Kiara'],
'Age':[10,30,45,36,23,33,41,19,21,18],
'City':['Tumkur','LA','Washington','Bengalury','Mysuru','Hubballi','Seoul','Tokyo','Mandya','Mumbai'],
'Salary':[10000,20000,np.nan,40000,50000,25000,np.nan,45000,55000,np.nan]
}
print(DataFrame)

df=pd.DataFrame(DataFrame)
print(df)

{'Name': ['Ankith', 'Arnav', 'Charles', 'Mini', 'Niki', 'Gopi', 'Kim', 'Steve', 'Praveen', 'Kiara'], 'Age': [10, 30, 45, 36, 23, 33, 41, 19, 21, 18], 'City': ['Tumkur', 'LA', 'Washington', 'Bengalury', 'Mysuru', 'Hubballi', 'Seoul', 'Tokyo', 'Mandya', 'Mumbai'], 'Salary': [10000, 20000, nan, 40000, 50000, 25000, nan, 45000, 55000, nan]}
      Name  Age        City   Salary
0   Ankith   10      Tumkur  10000.0
1    Arnav   30          LA  20000.0
2  Charles   45  Washington      NaN
3     Mini   36   Bengalury  40000.0
4     Niki   23      Mysuru  50000.0
5     Gopi   33    Hubballi  25000.0
6      Kim   41       Seoul      NaN
7    Steve   19       Tokyo  45000.0
8  Praveen   21      Mandya  55000.0
9    Kiara   18      Mumbai      NaN


In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes


In [37]:
df.describe()

Age        Salary
count  10.000000      7.000000
mean   27.600000  35000.000000
std    11.197222  16832.508231
min    10.000000  10000.000000
25%    19.500000  22500.000000
50%    26.500000  40000.000000
75%    35.250000  47500.000000
max    45.000000  55000.000000

In [38]:
print("Select Name and City")
print(df[['Name','City']])

Select Name and City
      Name        City
0   Ankith      Tumkur
1    Arnav          LA
2  Charles  Washington
3     Mini   Bengalury
4     Niki      Mysuru
5     Gopi    Hubballi
6      Kim       Seoul
7    Steve       Tokyo
8  Praveen      Mandya
9    Kiara      Mumbai


In [43]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [40]:
df.drop_duplicates()

Name  Age        City   Salary
0   Ankith   10      Tumkur  10000.0
1    Arnav   30          LA  20000.0
2  Charles   45  Washington      NaN
3     Mini   36   Bengalury  40000.0
4     Niki   23      Mysuru  50000.0
5     Gopi   33    Hubballi  25000.0
6      Kim   41       Seoul      NaN
7    Steve   19       Tokyo  45000.0
8  Praveen   21      Mandya  55000.0
9    Kiara   18      Mumbai      NaN

In [41]:
df.drop('City',axis=1)

Name  Age   Salary
0   Ankith   10  10000.0
1    Arnav   30  20000.0
2  Charles   45      NaN
3     Mini   36  40000.0
4     Niki   23  50000.0
5     Gopi   33  25000.0
6      Kim   41      NaN
7    Steve   19  45000.0
8  Praveen   21  55000.0
9    Kiara   18      NaN

In [42]:
avg_salary=df["Salary"].mean()

In [32]:
print(avg_salary)

35000.0


In [33]:
df.fillna({'Salary':avg_salary})

Name  Age        City   Salary
0   Ankith   10      Tumkur  10000.0
1    Arnav   30          LA  20000.0
2  Charles   45  Washington  35000.0
3     Mini   36   Bengalury  40000.0
4     Niki   23      Mysuru  50000.0
5     Gopi   33    Hubballi  25000.0
6      Kim   41       Seoul  35000.0
7    Steve   19       Tokyo  45000.0
8  Praveen   21      Mandya  55000.0
9    Kiara   18      Mumbai  35000.0

In [ ]:
df.duplicated() #It is showing False because no duplicate value in that row

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
df.drop_duplicates() #It doesn't has any duplicate value that's why it is showing original data without deleting any rows
#Duplicates means same rows repeating

Name  Age        City   Salary
0   Ankith   10      Tumkur  10000.0
1    Arnav   30          LA  20000.0
2  Charles   45  Washington      NaN
3     Mini   36   Bengalury  40000.0
4     Niki   23      Mysuru  50000.0
5     Gopi   33    Hubballi  25000.0
6      Kim   41       Seoul      NaN
7    Steve   19       Tokyo  45000.0
8  Praveen   21      Mandya  55000.0
9    Kiara   18      Mumbai      NaN